### ISSUE TITLE
Cannot create PlayerLifecycle (Shoebill 2.0-RC with Kotlin)

### ISSUE THREAD

**Issue by Alf21** [Shoebill/shoebill-common#5]
https://github.com/Shoebill/shoebill-common/blob/cb136033083c1d3053c30684076bf1ae9049daa2/src/main/java/net/gtaun/shoebill/common/player/PlayerLifecycleHolder.kt#L42

```
public class PlayerData extends PlayerLifecycleObject {
//...
    private Player player;
    public PlayerData(Player p) {
        super(p);
        player = p;
    }
//...
}
```

Causes this issue

```
[2017-12-10 02:31:56][ERROR][err] java.lang.Exception: No valid constructor available for class me.alf21.editorsystem.player.PlayerData.
[2017-12-10 02:31:56][ERROR][err] 	at net.gtaun.shoebill.common.player.PlayerLifecycleHolder$Companion$makeFactory$1.create(PlayerLifecycleHolder.kt:42)
[2017-12-10 02:31:56][ERROR][err] 	at net.gtaun.shoebill.common.player.PlayerLifecycleHolder$Companion$makeFactory$1.create(PlayerLifecycleHolder.kt:37)
[2017-12-10 02:31:56][ERROR][err] 	at net.gtaun.shoebill.common.LifecycleHolder.buildObjects(LifecycleHolder.kt:48)
[2017-12-10 02:31:56][ERROR][err] 	at net.gtaun.shoebill.common.player.PlayerLifecycleHolder$1.invoke(PlayerLifecycleHolder.kt:23)
[2017-12-10 02:31:56][ERROR][err] 	at net.gtaun.shoebill.common.player.PlayerLifecycleHolder$1.invoke(PlayerLifecycleHolder.kt:18)
[2017-12-10 02:31:56][ERROR][err] 	at net.gtaun.util.event.EventManager$registerHandler$1.handleEvent(EventManager.kt:65)
[2017-12-10 02:31:56][ERROR][err] 	at net.gtaun.util.event.EventManagerRoot.dispatchEvent(EventManagerRoot.kt:128)
[2017-12-10 02:31:56][ERROR][err] 	at net.gtaun.util.event.EventManager$DefaultImpls.dispatchEvent(EventManager.kt:114)
[2017-12-10 02:31:56][ERROR][err] 	at net.gtaun.util.event.EventManagerRoot.dispatchEvent(EventManagerRoot.kt:28)
[2017-12-10 02:31:56][ERROR][err] 	at net.gtaun.shoebill.SampEventDispatcher.onPlayerConnect(SampEventDispatcher.kt:97)
[2017-12-10 02:31:56][ERROR][err] 	at net.gtaun.shoebill.samp.SampCallbackManagerImpl$masterCallbackHandler$1$onPlayerConnect$1.invoke(SampCallbackManagerImpl.kt:49)
[2017-12-10 02:31:56][ERROR][err] 	at net.gtaun.shoebill.samp.SampCallbackManagerImpl$masterCallbackHandler$1$onPlayerConnect$1.invoke(SampCallbackManagerImpl.kt:29)
[2017-12-10 02:31:56][ERROR][err] 	at net.gtaun.shoebill.samp.SampCallbackManagerImplKt.forEachCatched(SampCallbackManagerImpl.kt:387)
[2017-12-10 02:31:56][ERROR][err] 	at net.gtaun.shoebill.samp.SampCallbackManagerImplKt.access$forEachCatched(SampCallbackManagerImpl.kt:1)
[2017-12-10 02:31:56][ERROR][err] 	at net.gtaun.shoebill.samp.SampCallbackManagerImpl$masterCallbackHandler$1.onPlayerConnect(SampCallbackManagerImpl.kt:49)
```

**Comment by 123marvin123** [comment]
Fixed with d81527689cef880490f07e27813ba92b5057961f
